namespace Disposer;

public interface ICsFileBuilder : IDisposable
{
    ICsFileBuilder AddAutoGeneratedHeader(string by);
    ICsFileBuilder AddStaticUsing(string usingStatement);
    ICsFileBuilder AddUsing(string usingStatement);
    ICsFileBuilder AddFileScopedNamespace(string namespaceName, bool condition);
    ICsFileBuilder AddNamespace(string namespaceName, bool condition);
    ICsFileBuilder AddCommentLine(string line);
    ICsFileBuilder AddEmptyLine(bool condition = true);
    ICsFileBuilder AddStatements(params string[] lines);
    ICsFileBuilder AddStatementsIf(bool condition, params string[] lines);
    ICsFileBuilder AddStatementAndStartBlock(string line);
    ICsFileBuilder AddIfBlock(string condition, params string[] lines);
    ICsFileBuilder EndBlock();
    ICsFileBuilder EndNamespace();
    string Build();
}
